plugin:
  description:
    name: Hydra
    version: 2.01
    description: Edge to protect your server
    authors:
      - Preceding
      - RealTrippy
      - Hydra Development 
    website: https://www.edgeac.xyz
  command:
    name: hydraac
    aliases:
      - hac
      - ach
      - anticheatss
storage:
  method: MONGO
  mongo:
    URI: "mongodb://127.0.0.1"
    database: "Edge"
